name: l_art_garden_mobil
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
 
  flutter:  # SDK de Flutter, necesario para cualquier aplicación Flutter.
    sdk: flutter

  soundpool: ^2.3.0  # Permite reproducir sonidos cortos simultáneamente.
  flutter_sound: ^8.3.9  # Proporciona funcionalidades para grabar y reproducir sonido.
  carousel_slider: ^4.2.1  # Permite crear carruseles de imágenes.
  dots_indicator: ^3.0.0  # Muestra indicadores de página (como puntos) que se suelen usar con carruseles.
  provider: ^6.1.1  # Proporciona una forma de gestionar el estado de la aplicación.
  internet_connection_checker: ^1.0.0+1  # Comprueba si el dispositivo está conectado a Internet.
  cupertino_icons: ^1.0.2  # Proporciona iconos al estilo iOS.
  http: ^1.2.0  # Permite hacer solicitudes HTTP.
  table_calendar: ^3.1.0  # Proporciona un widget de calendario interactivo.
  image_picker: ^1.0.7  # Permite seleccionar imágenes de la galería o tomar fotos con la cámara.
  image: ^4.1.7  # Proporciona funcionalidades para trabajar con imágenes.
  geolocator: ^7.6.2  # Proporciona funcionalidades de geolocalización.
  flutter_dialogs: ^2.1.1  # Permite mostrar diálogos y alertas.
  permission_handler: ^8.1.6  # Gestiona los permisos del dispositivo.
  google_maps_flutter: ^2.6.0  # Permite mostrar mapas de Google.
  geocoding: ^3.0.0  # Convierte entre coordenadas geográficas y nombres de lugares.
  google_sign_in: ^6.2.1  # Permite la autenticación con Google.
  flutter_shimmer: ^2.1.2  # Proporciona un efecto de brillo para indicar la carga de contenido.
  animated_text_kit: ^4.2.2  # Proporciona animaciones de texto.
  shimmer: ^3.0.0
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/usuario.png
    - assets/images/yellow_flowers_edited.png
    - assets/images/carouselImages/mother.jpg
    - assets/images/carouselImages/sValentin.jpg
    - assets/images/icons/Logo L_Art_Garden_white.png
    - assets/sounds/lsound.mp3
    - assets/sounds/L-Art-Garden-Sounds.mp3
    - assets/images/Logo_L_Art_garden_Pre_design_small.png
    - assets/images/Logo_L_Art_garden_Pre_design_small_User.png

  fonts:
    - family: FlowerLetter
      fonts:
        - asset: assets/fonts/LobsterTwo-Regular.ttf
    - family: SunFLower
      fonts:
        - asset: assets/fonts/SendFlowers-Regular.ttf
    - family: CuteFlower
      fonts:
        - asset: assets/fonts/Sunflower-Light.ttf
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-VariableFont_wght.ttf
    - family: Mont
      fonts:
        - asset: assets/fonts/MontserratAlternates-Light.ttf 
    - family: Capri
      fonts:
        - asset: assets/fonts/Capriola-Regular.ttf     
    - family: Cinzel
      fonts:
        - asset: assets/fonts/CinzelDecorative-Bold.ttf   

